### ISSUE TITLE
As an admin I should be able to install passbolt under mydomain.tld/passbolt

### ISSUE THREAD

**Issue by klugerama** [passbolt/passbolt_api#81]
I am integrating this into an Apache installation that already has other web documents and files that should be available at the web root. With this in mind, I aimed to install it under a directory, "/passbolt".

This proved to be very problematic...it looks like the default configuration assumes that it will be served from the root web directory. I had to massage quite a few settings and a few hardcoded paths to allow this, as well as create a few Apache redirects and aliases.

IIRC:

`app/Config/core.php` 
    --> `Configure::write('App.fullBaseUrl', 'https://my.domain.name/passbolt');`
`app/View/Pages/home.ctp` (hardcoded paths to steal.production.js weren't resolving correctly)
`app/View/Layouts/login.ctp` (same)
and under the Apache configuration:

```
Redirect /recover /passbolt/recover #due to hardcoded path in the browser plugin
Redirect /passbolt/passbolt /passbolt
Alias /passbolt /var/www/passbolt/app/webroot

<Directory /var/www/passbolt/app/webroot>
    Options FollowSymLinks
    DirectoryIndex index.php
    AllowOverride All
</Directory>
```

Any chance of making this a little less painful in the future?

**Comment by stripthis** [comment]
Hi @klugerama, thank you for the bug report. We'll work on a fix for this.
ref. PASSBOLT-2111

**Comment by cypherkey** [comment]
I opened a similar issue under the passbolt-docker project as I was trying to run the docker image behind a reverse proxy. See issue 13 under passbolt-docker.

**Comment by cedricalfonsi** [comment]
Hello @cypherkey,

We're currently working on this issue, a fix should come with the next release v1.5.2.

Most of the issues we fixed are related to hardcoded urls. If you're interested to take a look of what we've done before the release, I attached the patches to this comment.

Regarding the apache configuration, we have few differences, but it could be relative to our different environment. We don't use alias and our directory target the cake root directory :
`Listen 8081

<VirtualHost *:8081>
        DocumentRoot /var/www
        RewriteEngine On
    <Directory /var/www/passbolt>
            Redirect /passbolt/passbolt /passbolt
            Options Indexes FollowSymLinks MultiViews
            AllowOverride All
            Order allow,deny
            allow from all
    </Directory>
</VirtualHost>`

For now we still cannot avoid the redirect rule /passbolt/passbolt to passbolt. I created another ticket to take care of it.

Thank you for your report, it helps us a lot.

API : [PASSBOLT-2111.txt](https://github.com/passbolt/passbolt_api/files/1055181/PASSBOLT-2111.txt)
Plugin : [PASSBOLT_2111.txt](https://github.com/passbolt/passbolt_api/files/1055182/PASSBOLT_2111.txt)

**Comment by cedricalfonsi** [comment]
Fixed with v1.6.0

**Comment by ReasyEasyPeasy** [comment]
Hey,
I still have some Issues with passbolt behind a reverse proxy.

reverse-proxy(nginx) in docker and passbolt+nginx in docker
client myUrl/passbolt -> nginx ->127.18.0.5:80 ->(nginx+passbolt)

 I'm using passbolt 1.6.9. 

I changed app/Config/core.php
--> Configure::write('App.fullBaseUrl', 'https://my.domain.name/passbolt');
Home and login links are still pointing to https://my.domain.name and css/js GET-request  trying to access 
https://my.domain.name/css/login.min.css
instead of https://my.domain.name/passbolt/css/login.min.css
So the site is just plain text. No style
reverse-proxy-conf:
location  /passbolt {
	rewrite /passbolt/(.*) /$1 break;
	proxy_set_header X-Forwarded-Host $host;
	proxy_set_header X-Forwarded-Server $host;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_pass http://docker-passbolt;
	proxy_redirect off;
	add_header X-Frame-Options ALLOW;
}

adding location like this to the reverse-proxy:
location /js {
proxy_pass http://docker-passbolt;
}
location /css {
proxy_pass http://docker-passbolt;
}
make the site look normal. But this is not a solution.
