### ISSUE TITLE
Adding user to existing group fails

### ISSUE THREAD

**Issue by shochdoerfer** [passbolt/passbolt_api#82]
I want to add an user to an existing group but the operation failed. In the error.log file on the server I can see the following error:
```
2017-06-04 10:19:57 Error: [ValidationException] Could not validate Secret
Request URL: /groups/295d947b-2d5c-43c4-9989-f6de4e890562.json
Stack Trace:
#0 [internal function]: GroupsController->edit('295d947b-2d5c-4...')
#1 /srv/passbolt/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(GroupsController), Array)
#2 /srv/passbolt/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /srv/passbolt/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(GroupsController), Object(CakeRequest))
#4 /srv/passbolt/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
```
In the Javascript console of my browser I got the following error:
```
passbolt.js:507 Uncaught TypeError: Cannot read property 'name' of undefined
    at a.{mad.bus.element} group_edit_save_error (passbolt.js:507)
    at HTMLDivElement.<anonymous> (passbolt.js:44)
    at HTMLDivElement.dispatch (passbolt.js:7)
    at HTMLDivElement.m.handle (passbolt.js:7)
    at Object.trigger (passbolt.js:7)
    at HTMLDivElement.<anonymous> (passbolt.js:7)
    at Function.each (passbolt.js:6)
    at Z.fn.init.each (passbolt.js:6)
    at Z.fn.init.trigger (passbolt.js:7)
    at passbolt.js:167
```

Adding the same user to a new group works fine. The group I wanted to add the user to is older than the user account itself. Not sure if this matters somehow.

**Comment by stripthis** [comment]
Hi @shochdoerfer, thanks for the bug report @cedricalfonsi will look into it this sprint.
PASSBOLT-2112

**Comment by shochdoerfer** [comment]
Not sure if this is related but sometimes when I edit a group users I can see them 2 or 3 times. Like, I assigned 2 users to the group but actually see 6 users assigned - 3 times the same 2 users. Maybe a side-effect due to a JS error. I tried this with the Vivaldi browser and the Chrome extension.

**Comment by cedricalfonsi** [comment]
Hello @shochdoerfer,

Can you give me more details regarding the versions of the API & the plugin in use ? 
If you were part of the early testers of the 1.5.0 release, did you switch to the public 1.5.1 release ?
Is the main bug you reported can be reproduced with another group ? 

For the second bug you reported, does it happen when you're editing a group from the right sidebar. We had a similar bug that we fixed with the 1.5.1 release :
PASSBOLT-2060 Editing a group opened from the right the sidebar shouldn't create duplicated entries in the dialog

**Comment by shochdoerfer** [comment]
API and plugin version are 1.5.1 - We were not early testers, we used an older version of Passbolt - can't remember which, sorry - and upgraded to 1.5.1 once it was out.

We had 2 groups set up before a few new users signed up. The error that I reported above - I want to add an user to an existing group but the operation failed - happens just with one of the two groups. The other error - seeing multiple accounts assigned to one group - happen with the other group. 

For the second error, this is what I see in the browser:
![passbolt_groups_error](https://cloud.githubusercontent.com/assets/596449/26789644/34f8a444-4a11-11e7-9f8c-9dd55d1b67b7.png)

**Comment by cedricalfonsi** [comment]
@shochdoerfer
We'd like to have a call with you to puzzle out this issue.
Can you send your availabilities to contact@passbolt.com ? Today I have some, I'd be glad to help you.

**Comment by agrgic** [comment]
@cedricalfonsi @shochdoerfer I have the same issue, when I want to add a user to a group

**Comment by stripthis** [comment]
@agrgic this issue was solved for @shochdoerfer by clearing firefox cache I believe.

**Comment by shochdoerfer** [comment]
Correct. Looks like the server was caching the JS a bit too aggressively.

**Comment by agrgic** [comment]
@shochdoerfer @stripthis unfortunately this didn't fix my issue, still getting an error:

Uncaught TypeError: Cannot read property 'length' of null
    at Object.<anonymous> (passbolt.js:505)
    at n.render (passbolt.js:143)
    at Function.<anonymous> (passbolt.js:143)
    at r.render (passbolt.js:60)
    at Function.renderTo (passbolt.js:60)
    at Function.renderAs (passbolt.js:60)
    at Function.render (passbolt.js:60)
    at Function.render (passbolt.js:141)
    at a.insertItem (passbolt.js:189)
    at a.insertItem (passbolt.js:195)

Using Chrome 59

**Comment by stripthis** [comment]
@agrgic  can you create a different issue since the error messages are not the same? Please provide a step by step description on how you trigger the problem, screenshots, information about your environment.

**Comment by matejvelikonja** [comment]
I'm experiencing the same issue as the first comment.
I'm using the latest develop version (docker).

Has anyone found a solution to this?

Clearing cache, changing browser did not help.

**Comment by matejvelikonja** [comment]
Figure out what was the problem:
- the user forgot login informations
- the user has been deleted from GUI
- new user with same email has been created
- new user registered
- I could not add this new user to a group
- **I've manually deleted everything related to old user from database**
- The new user can now be added to the group
